### ISSUE TITLE
Add instructions on setting Akri Instance OwnerReference when requesting Akri Resources

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri-docs#35]
Instead of using the Akri Controller, Akri users can deploy their own Kubernetes Objects (Pods, Deployments, DaemonSets, etc) to use the Kubernetes resources created by Akri. This is explained in the [Requesting Akri Resources documentation](https://docs.akri.sh/user-guide/requesting-akri-resources). However, if a device goes offline and an Instance is deleted, the workload will remain. A way to avoid this is to add [OwnerReferences](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/) like the Akri Controller does by default. This ensures that the Pod/Deployment/Job only runs so long as the device exists:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: akri-broker
  ownerReferences:
  - apiVersion: akri.sh/v0
    blockOwnerDeletion: true
    controller: true
    kind: Instance
    name: akri-udev-video-985ff9
    uid: be3363ce-c84a-4c2e-8b68-d5186d48fb7b
spec:
  containers:
  - name: akri-broker
    image: nginx:latest
    resources:
      limits:
        akri.sh/akri-udev-video-985ff9: "1"
      requests:
        akri.sh/akri-udev-video-985ff9: "1"
```
The uid can be obtained by running `kubectl get akrii --output=json | jq ".items[].metadata.uid"`
We should provide a script -- maybe a series of jqueries -- for generating the `OwnerReference` that can be added to a `PodSpec`.
